ControleClientes/Controllers/ContaController.cs
using AutoMapper;
using ControleClientes.Aplicacao.Interfaces;
using ControleClientes.Dominio.Entidades;
using ControleClientes.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleClientes.Controllers
{
    public class ContaController : Controller
    {
        private readonly IContaApp _contaApp;
        private readonly ITipoContaApp _tipoContaApp;
        private readonly IClienteApp _clienteApp;
        private readonly IAgenciaApp _agenciaApp;

        public ContaController(IContaApp contaApp, ITipoContaApp tipoContaApp, IClienteApp clienteApp, IAgenciaApp agenciaApp)
        {
            _contaApp = contaApp;
            _tipoContaApp = tipoContaApp;
            _clienteApp = clienteApp;
            _agenciaApp = agenciaApp;
        }

        // GET: Conta
        public ActionResult Index()
        {
            var contaViewModel = Mapper.Map<List<ContaViewModel>>(_contaApp.List().ToList());

            return View(contaViewModel);
        }

        // GET: Conta/Details/5
        public ActionResult Details(int numeroConta)
        {
            var conta = _contaApp.BuscarPorNumeroConta(numeroConta);
            var contaViewModel = Mapper.Map<Conta, ContaViewModel>(conta);

            return View(contaViewModel);
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            ViewBag.TipoContasList = new SelectList(Mapper.Map<List<TipoContaViewModel>>(_tipoContaApp.List().ToList()), "IdTipoConta", "NomeTipoConta");
            ViewBag.ClientesList = new SelectList(Mapper.Map<List<ClienteViewModel>>(_clienteApp.List().ToList()), "IdCliente", "Nome");
            ViewBag.AgenciasList = new SelectList(Mapper.Map<List<AgenciaViewModel>>(_agenciaApp.List().ToList()), "IdAgencia", "NomeAgencia");

            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContaViewModel conta)
        {
            if (ModelState.IsValid)
            {
                var _clienteDomain = Mapper.Map<ContaViewModel, Conta>(conta);

                _contaApp.Add(_clienteDomain);

                return RedirectToAction("Index");
            }

            return View(conta);
        }

        // GET: Conta/Transferir/5
        public ActionResult Transferir(int numeroConta)
        {
            var conta = _contaApp.BuscarPorNumeroConta(numeroConta);
            var contaViewModel = Mapper.Map<Conta, ContaViewModel>(conta);

            var listaContas = _contaApp.List().ToList();
            listaContas.Remove(conta);

            ViewBag.ListaContas = new SelectList(Mapper.Map<List<ContaViewModel>>(listaContas), "NumeroConta", "NumeroContaCliente");

            return View(contaViewModel);
        }

        // POST: Conta/Transferir/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Transferir(FormCollection form)
        {
            try
            {
                var numContaOrigem = form["NumeroConta"];
                var numContaDestino = form["ContaDestino"];
                var valor = Convert.ToDouble(form["Valor"]);

                _contaApp.Transferir(numContaOrigem, numContaDestino, valor);

                TempData["Sucesso"] = $"Transferência no valor de {valor} entre a conta {numContaOrigem} e {numContaDestino} realizada com sucesso!";
            }
            catch(Exception ex)
            {
                TempData["Erro"] = ex.Message;
            }

            return RedirectToAction("Index");
        }
    }
}

ControleClientes/Controllers/TipoContaController.cs
using AutoMapper;
using ControleClientes.Aplicacao.Interfaces;
using ControleClientes.Dominio.Entidades;
using ControleClientes.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ControleClientes.Controllers
{
    public class TipoContaController : Controller
    {
        private readonly ITipoContaApp _tipoContaApp;

        public TipoContaController(ITipoContaApp tipoContaApp)
        {
            _tipoContaApp = tipoContaApp;
        }

        // GET: TipoConta
        public ActionResult Index()
        {
            var tipoContaviewModel = Mapper.Map<IEnumerable<TipoConta>, IEnumerable<TipoContaViewModel>>(_tipoContaApp.List());

            return View(tipoContaviewModel);
        }

        // GET: TipoConta/Details/5
        public ActionResult Details(int id)
        {
            var tipoConta = _tipoContaApp.Find(id);
            var tipoContaViewModel = Mapper.Map<TipoConta, TipoContaViewModel>(tipoConta);

            return View(tipoContaViewModel);
        }
    }
}

ControleClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle de Clientes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Agencia", "Index", "Agencia")</li>
                    <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Contas", "Index", "Conta")</li>
                    <li>@Html.ActionLink("Tipos de Conta", "Index", "TipoConta")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle de Clientes - Luiz Henrique da Silva</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>